### ISSUE TITLE
Add a note about the config requirement to installation instructions

### ISSUE THREAD

**Issue by richardthebrave** [montlewis/perch-redactor-default#1]
In the Perch config.php file (`perch/config/config.php`) the following line is required to enable custom editor configurations:

`define('PERCH_CUSTOM_EDITOR_CONFIGS',` true);

I'm new to editor configs and it took a few minutes to figure out what I was missing – perhaps this will help others. Thanks for putting this out there! FYI I found you via Clive Walker's Perchology newsletter.

**Comment by montlewis** [comment]
Thanks, Richard. I've added that to the read me. Sorry it wasn't there!
